# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pickup-option"
client_id = "b8c8c3462d759b9b840715d8c9b9a87d"
application_url = "https://dat-icq-several-enlargement.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dat-icq-several-enlargement.trycloudflare.com/auth/callback",
  "https://dat-icq-several-enlargement.trycloudflare.com/auth/shopify/callback",
  "https://dat-icq-several-enlargement.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extension-test-store2.myshopify.com"
